# Generated by Django 4.0.1 on 2022-05-07 11:32

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to=api.models.get_upload_path),
        ),
    ]
